#pragma once

#include <QDateTime>
#include <QList>
#include <QObject>
#include <QString>
#include <QStringList>

namespace Robomongo
{
    /**
     * @brief One executed command in the shared history.
     */
    struct HistoryEntry
    {
        QDateTime timestamp;
        QString connectionName;
        QString databaseName;
        QString command;
        bool autoGenerated = false;    // Explorer-generated query vs typed by user
    };

    /**
     * @brief Command history shared by the console input (Up/Down recall)
     *  and the View > History dock.
     *
     * Storage: JSONL file ~/.romo/history.jsonl (one JSON object per line,
     * rewritten on every change). Entries are unique per (connection, command):
     * re-running a command moves it to the top; consecutive duplicates are
     * ignored. At most kMaxEntriesPerConnection unique entries are kept per
     * connection. List order: newest first.
     *
     * All operations must happen on the GUI thread (no locking).
     */
    class HistoryStore : public QObject
    {
        Q_OBJECT

    public:
        static HistoryStore &instance();

        static constexpr int kMaxEntriesPerConnection = 500;

        void add(QString const &connectionName, QString const &databaseName,
                 QString const &command, bool autoGenerated);

        QList<HistoryEntry> const &entries() const { return _entries; }
        QStringList connectionNames() const;
        void remove(QString const &connectionName, QString const &command);
        void clear();

    Q_SIGNALS:
        void entryAdded(Robomongo::HistoryEntry const &entry);
        /** Emitted on every structural change (add/remove/clear). */
        void changed();

    private:
        HistoryStore();
        void load();
        void save() const;
        void trimConnection(QString const &connectionName);

        QList<HistoryEntry> _entries;    // newest first
    };
}
