#include "robomongo/core/history/HistoryStore.h"

#include <QDir>
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSet>
#include <QTextStream>

#include <algorithm>

namespace Robomongo
{
    namespace
    {
        QString historyFilePath()
        {
            return QDir::homePath() + "/.romo/history.jsonl";
        }
    }

    HistoryStore &HistoryStore::instance()
    {
        static HistoryStore store;
        return store;
    }

    HistoryStore::HistoryStore()
    {
        load();
    }

    void HistoryStore::add(QString const &connectionName, QString const &databaseName,
                           QString const &command, bool autoGenerated)
    {
        QString const trimmed = command.trimmed();
        if (trimmed.isEmpty() || connectionName.isEmpty())
            return;

        // Commands are unique per connection: drop any older occurrence of the
        // same command (re-running moves it to the top) and treat a repeat of
        // the most recent entry as a consecutive duplicate (skip entirely).
        for (int i = 0; i < _entries.size();) {
            HistoryEntry const &existing = _entries[i];
            bool const same = existing.connectionName == connectionName
                              && existing.command.trimmed() == trimmed;
            if (same) {
                if (i == 0)
                    return;
                _entries.removeAt(i);
                continue;
            }
            ++i;
        }

        HistoryEntry entry;
        entry.timestamp = QDateTime::currentDateTime();
        entry.connectionName = connectionName;
        entry.databaseName = databaseName;
        entry.command = trimmed;
        entry.autoGenerated = autoGenerated;
        _entries.prepend(entry);

        trimConnection(connectionName);
        save();

        Q_EMIT entryAdded(entry);
        Q_EMIT changed();
    }

    void HistoryStore::remove(QString const &connectionName, QString const &command)
    {
        for (int i = 0; i < _entries.size(); ++i) {
            if (_entries[i].connectionName == connectionName
                    && _entries[i].command == command) {
                _entries.removeAt(i);
                save();
                Q_EMIT changed();
                return;
            }
        }
    }

    QStringList HistoryStore::connectionNames() const
    {
        QStringList result;
        QSet<QString> seen;
        for (HistoryEntry const &entry : _entries) {
            if (seen.contains(entry.connectionName))
                continue;
            seen.insert(entry.connectionName);
            result.append(entry.connectionName);
        }
        return result;
    }

    void HistoryStore::clear()
    {
        if (_entries.isEmpty())
            return;
        _entries.clear();
        save();
        Q_EMIT changed();
    }

    void HistoryStore::trimConnection(QString const &connectionName)
    {
        int kept = 0;
        for (int i = 0; i < _entries.size();) {
            if (_entries[i].connectionName == connectionName && ++kept > kMaxEntriesPerConnection)
                _entries.removeAt(i);
            else
                ++i;
        }
    }

    void HistoryStore::load()
    {
        QFile file(historyFilePath());
        if (!file.open(QFile::ReadOnly | QFile::Text))
            return;

        QTextStream in(&file);
        while (!in.atEnd()) {
            QJsonParseError error;
            QJsonDocument const doc =
                QJsonDocument::fromJson(in.readLine().toUtf8(), &error);
            if (error.error != QJsonParseError::NoError || !doc.isObject())
                continue;

            QJsonObject const obj = doc.object();
            HistoryEntry entry;
            entry.timestamp = QDateTime::fromString(obj.value("t").toString(), Qt::ISODate);
            entry.connectionName = obj.value("c").toString();
            entry.command = obj.value("q").toString();
            entry.databaseName = obj.value("d").toString();
            entry.autoGenerated = obj.value("a").toBool(false);
            if (entry.connectionName.isEmpty() || entry.command.isEmpty())
                continue;
            _entries.append(entry);   // file is written oldest-first
        }

        // Reverse to newest-first order.
        std::reverse(_entries.begin(), _entries.end());
    }

    void HistoryStore::save() const
    {
        QDir().mkpath(QDir::homePath() + "/.romo");

        QFile file(historyFilePath());
        if (!file.open(QFile::WriteOnly | QFile::Truncate | QFile::Text))
            return;

        QTextStream out(&file);
        // Newest-first list is written oldest-first, so a crash-append style
        // reader would still see a chronologically ordered file.
        for (auto it = _entries.crbegin(); it != _entries.crend(); ++it) {
            QJsonObject obj;
            obj.insert("t", it->timestamp.toString(Qt::ISODate));
            obj.insert("c", it->connectionName);
            if (!it->databaseName.isEmpty())
                obj.insert("d", it->databaseName);
            obj.insert("q", it->command);
            if (it->autoGenerated)
                obj.insert("a", true);
            out << QString::fromUtf8(QJsonDocument(obj).toJson(QJsonDocument::Compact)) << "\n";
        }
    }
}
